language: generic
services:
  - docker

before_install:
  - docker build -t fatihkelesdev/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true fatihkelesdev/docker-react npm run test -- --coverage


